//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncmentTable
    {
        public int announcmentID { get; set; }
        public System.DateTime announcmentDate { get; set; }
        public string announcmentMessage { get; set; }
        public string announcmentSend { get; set; }
    }
}
