//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTable
    {
        public int appointmentID { get; set; }
        public int patientID { get; set; }
        public string patientName { get; set; }
        public string appointmentReason { get; set; }
        public int idDoctor { get; set; }
        public string doctorName { get; set; }
        public int idNurse { get; set; }
        public string nurseName { get; set; }
        public System.DateTime appointmentDate { get; set; }
        public string notes { get; set; }
    }
}
