//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseTable
    {
        public int nurseID { get; set; }
        public string nurseName { get; set; }
        public System.DateTime hireDate { get; set; }
    }
}
